services:
  - type: web
    name: fgsm-backend
    runtime: python
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app_fgsm:app --host 0.0.0.0 --port $PORT